@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nowebsite.maker.furnitureplan.common.entity;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;