@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nowebsite.maker.furnitureplan.blocks.cookingUtensils.blockentities.states;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;