@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nowebsite.maker.furnitureplan.blocks.utensils.blockentities.renderers;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;