@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nowebsite.maker.furnitureplan.common.block.abstraction.generators;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;